### ISSUE TITLE
BMCoreUI breaks MFA 8.5.2 asset list

### ISSUE THREAD

**Issue by ikergomez-ikusi** [BogdanMihaiciuc/BMCoreUI#4]
Hello,

After installing the BMCoreUI extension, the asset list for the asset advisor in MFA 8.5.2 disappears. The scroll still appears but on a blank space. I don't know if it has something to do with the official collection widget that the mashup uses to create the list of assets.

Thank you.

Best regards,
Iker

**Comment by BogdanMihaiciuc** [comment]
This is because the built in collection widget uses a fork of Core UI whose API has changed (the platform version is technically private so it doesn't need a stable API). Unfortunately this leads to conflicts because the Core UI API is no longer compatible with the built in collection.

I don't yet have a fix for this and don't plan on replicating the API changes from the Thingworx version, but I will look into possible workarounds.

In the meantime, the only advice I can give is to not use Core UI and its dependent widgets if you know you will be using the built in collection widget.

**Comment by ikergomez-ikusi** [comment]
Hello Bogdan,
OK, I understand the problem. Thanks a lot for your help and fast reply!! 
Please let me know if you find a fix or workaround.
Best regards,
Iker

**Comment by BogdanMihaiciuc** [comment]
Consider using [this](https://github.com/ptc-iot-sharing/BMCoreUIWidgets) as a workaround. It is a package containing core ui and all of its widgets delivered in a private container.

The only downside is that you can't choose which widgets you want or not. It's either the whole package or nothing.

**Comment by ikergomez-ikusi** [comment]
Thanks a lot for your help and great work!! I'll try the workaround package ASAP.
Regards,
Iker
