### ISSUE TITLE
IPad issues

### ISSUE THREAD

**Issue by ldellaversano** [BogdanMihaiciuc/BMCoreUI#6]
Hi, in our project, we have problems with IPad use mode.

We are unable to click on dropdwn/folding panel/value diplay widgets when these objects are into BMCollection. We are able to click only button widgets into BMCollection.

Our BMCollection version is 2.5.4 
![image](https://user-images.githubusercontent.com/72251747/94907489-8f46ea80-04a0-11eb-997f-a06cbd30b6e4.png)
Our TWX version is 8.4.3-b2219 .

Do you have any suggestions?

**Comment by BogdanMihaiciuc** [comment]
You should be able to resolve this issue by updating to core ui v2.6.1.

If this update resolves your problem with the folding panels, please close this issue.

**Comment by ldellaversano** [comment]
Hi Bogdan,
we tested and we see 
![image](https://user-images.githubusercontent.com/72251747/97727382-9fb6a900-1ad0-11eb-9c1c-bdb4be311300.png) now.
Unfortunately we didn't see any improvement. Folding Panel doesn't work yet for IPad.

We await your feedback.
Thanks

**Comment by BogdanMihaiciuc** [comment]
Can you confirm that **`BMCoreUI`** is at version 2.6.1?

**Comment by ldellaversano** [comment]
Yes Bogdan,
This is the confirmation
![image](https://user-images.githubusercontent.com/72251747/97844962-37dcaa00-1cec-11eb-9e52-57e60c2cd42c.png)

**Comment by BogdanMihaiciuc** [comment]
You will also need to disable iScroll on the collections where you are using folding panels because that will also interfere with the event handling. Some of the properties that can cause iScroll to be enabled are:

- pinned headers and footers
- masonry or stack layout
- scrollbar styles
- explicitly enabling it in advanced settings or the equivalent `AlwaysUseCustomScroller` properties

Note that for best results you will need to disable interaction with elements that appear on the folding panel clickable area, otherwise you will need to tap on the empty areas only. A CSS class with `pointer-events: none;` should do the trick here.

**Comment by ldellaversano** [comment]
Hi Bogdan, it works now!
Great Job!!!

Thank you so much
